### ISSUE TITLE
Error handling should fail earlier and louder

### ISSUE THREAD

**Issue by sir4ur0n** [ag91/code-compass#22]
After pressing pause on trying to make `code-compass` work (thank you by the way on fixing the variables not being passed to the async process!), I tried again today on my repo.
But `c/show-hotspots` failed (as in, the displayed `zoomable.html` does not work with a javascript error) while I had no error in Emacs whatsoever :sob: 

I just spent some time investigating why and while I found the problem (I will open another issue about that), I think that `code-compass` should make errors more visible to the user, and fail fast to simplify investigation.

Example:
* when the `code-maat` command for `revisions` fails (shell return code `1`), the process continues rather than aborting immediately. The generated `revisions.csv` contains garbage content:
```
Invalid argument:  git2: Failed to parse the given file - is it a valid logfile?
This is Code Maat, a program used to collect statistics from a VCS.
Version: 1.0-SNAPSHOT

Usage: program-name -l log-file [options]

Options:
  -l, --log LOG                                         Log file with input data
  -c, --version-control VCS                             Input vcs module type: supports svn, git, git2, hg, p4, or tfs
[...]
```
* the process continues like everything is ok then spectacularly :smile: crashes:
```
Produce json...
Traceback (most recent call last):
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 232, in <module>
    run(args)
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 195, in run
    raw_weights = parse_csv(
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 90, in parse_csv
    return [parse_action(row) for row in r]
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 90, in <listcomp>
    return [parse_action(row) for row in r]
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 114, in parse_element_weight
    weight = float(csv_row[weight_column])  # Assert not zero?
ValueError: could not convert string to float: ' a program used to collect statistics from a VCS.'
```

Below the full logs:
```
Producing git report...
(Shell command succeeded with no output)
Producing code-maat revisions report for <REDACTED>...
(Shell command failed with code 1 and no output)
Producing cloc report...
(Shell command succeeded with no output)
Produce json...
Traceback (most recent call last):
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 232, in <module>
    run(args)
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 195, in run
    raw_weights = parse_csv(
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 90, in parse_csv
    return [parse_action(row) for row in r]
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 90, in <listcomp>
    return [parse_action(row) for row in r]
  File "/tmp/code-compass-<REDACTED>/csv_as_enclosure_json.py", line 114, in parse_element_weight
    weight = float(csv_row[weight_column])  # Assert not zero?
ValueError: could not convert string to float: ' a program used to collect statistics from a VCS.'
```

:warning: notice in particular `(Shell command failed with code 1 and no output)`

**Comment by ag91** [comment]
oh, we don't leave in a perfect world yet?! XD Sorry, I got bitten by that a few times myself but I never addressed the issue.
Let me see if I can find an easy way out
